# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # For production dependencies
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "direct"

  # For dev/test dependencies
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements-dev.txt
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps-dev"
    labels:
      - "dependencies"
      - "dev-dependencies"
    allow:
      - dependency-type: "direct"

