[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mini_rag"
version = "0.0.1"
description = "mini RAG internship project"
authors = [{name = "Your Name"}]
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]
